[WIP]第7回目の課題
mf-sakura/golang_study pull request #15
Opened 2020-04-01 05:47 UTC by TaKO8Ki

先にPRだけ作っておく

2020-04-07 07:12 UTC, mf-sakura commented
これは宿題ではなくて、講義で使うコード？

2020-04-07 07:15 UTC, TaKO8Ki commented
sample/以下でGoにおけるテストとはみたいな話（gotests, TestMainの説明も）をして、DB操作部分のテストの例を一つくらい示す感じで行こうかなと思っていました！
@mf-sakura

2020-04-07 07:22 UTC, mf-sakura commented
良さそう！
PR名から宿題のコードと思ってた...
ある程度完成したら教えて欲しい〜

2020-04-07 07:32 UTC, TaKO8Ki commented
@mf-sakura 
あ、確かに名前間違ってましたw

2020-04-07 07:35 UTC, TaKO8Ki commented
@mf-sakura 
DBのところのテストどんな感じにやるかちょっと迷ってるんですが、sqlmock使ってdbをmockしてやってみたいな感じでいいと思いますか？

2020-04-07 07:49 UTC, mf-sakura commented
@TaKO8Ki 
sqlmock、mysqlのmockにruby開発者が慣れてそうであれば良いと思う。
SQL多くなってくると結構煩雑なので、DB立ててテストでクエリ打つ方が分かりやすいかなと思ってた。

2020-04-07 07:55 UTC, TaKO8Ki commented
@mf-sakura 
普通にtest用のdb立てる方が分かりやすそうですね。

2020-04-07 18:17 UTC, TaKO8Ki commented
@mf-sakura 
なんとなくコード実装し終えました！

2020-04-08 02:53 UTC, mf-sakura commented
見ます！

2020-04-08 03:18 UTC, mf-sakura requested changes
@TaKO8Ki 
コメントしました〜
`test/sample/sample`にバイナリが含まれてるから、これもgit rmしておいて欲しい:pray:

2020-04-08 03:18 UTC, mf-sakura commented on test/api/interfaces/database/user_repository_test.go
> +	}
connectionを毎回貼り直す必要はないから、TestMainに移して欲しい。
GlobalにConnectionを保持しておいて、この関数ではMustBegin()でsqlx.Txを返す様にすれば良い気がする。

2020-04-08 03:18 UTC, mf-sakura commented on test/api/interfaces/database/user_repository_test.go
> +var sqlHandler infrastructure.SQLHandler
この変数って必要なんだっけ？

2020-04-08 03:18 UTC, mf-sakura commented on test/api/interfaces/database/user_repository_test.go
> +		db *sqlx.DB
Txをloopの中で渡すのは良いと思うので、argsからdbを削除して欲しい。

2020-04-08 03:18 UTC, mf-sakura commented on test/api/interfaces/controllers/user_controller.go
> +	return c.JSON(http.StatusOK, &users)
```
if err != nil {
	return err
}
return c.JSON(http.StatusOK, &users)
```
↑の処理が重複してるので↓みたいな実装の方が読みやすいと思ったんだけど、どうだろう？
```suggestion
	var err error
	var users domain.Users
	if firstName != "" {
		users, err = database.FirstNameLike(controller.db, firstName)
	} else {
		users, err = database.FindAll(controller.db)
	}
	if err != nil {
		return err
	}
	return c.JSON(http.StatusOK, &users)
```

2020-04-08 03:45 UTC, TaKO8Ki commented on test/api/interfaces/controllers/user_controller.go
> +	return c.JSON(http.StatusOK, &users)
同じような感じにしようとしたらなんかエラー出るなーと思ってたんですが、よくみたらこうなってました！
```go
users, err := database.FirstNameLike(controller.db, firstName)
```
修正しましたー

2020-04-08 03:46 UTC, TaKO8Ki commented
@mf-sakura
全体的に修正しましたー

2020-04-08 03:47 UTC, TaKO8Ki commented on test/api/interfaces/database/user_repository_test.go
> +var sqlHandler infrastructure.SQLHandler
消すの忘れてたんですが、今回の修正でTestMainで使うようになったので残しました！

2020-04-08 03:49 UTC, mf-sakura commented on test/api/interfaces/controllers/user_controller.go
> +	return c.JSON(http.StatusOK, &users)
👍

2020-04-08 03:51 UTC, mf-sakura commented on test/api/interfaces/database/user_repository_test.go
> +var sqlHandler infrastructure.SQLHandler
`sqlHandler.Conn`しか使ってないので、sqlx.DBを直接持つのが良い気がする！

2020-04-08 03:52 UTC, mf-sakura commented
@TaKO8Ki 
1点コメントしました:pray:

2020-04-08 04:16 UTC, TaKO8Ki commented on test/api/interfaces/database/user_repository_test.go
> +var sqlHandler infrastructure.SQLHandler
修正しました！！

2020-04-08 04:17 UTC, TaKO8Ki commented
あとはesa書いていきます。

2020-04-08 11:40 UTC, mf-sakura approved these changes
LGTM!

2020-04-09 01:40 UTC, TaKO8Ki commented
マージしますー
@mf-sakura

2020-04-09 01:45 UTC, merged